name: Build release
on: 
  push:
    tags:
    - '*'

jobs:
  build_gesso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          npm ci
          npm run build
      - run: |
          rm -rf node_modules
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'slac.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig source/*'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'slac.zip'
          replacesArtifacts: true
          allowUpdates: true
