name: Build release
on:
  push:
    tags:
      - '**'
concurrency:
  group: release
  queue: max

jobs:
  build_gesso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: |
          npm i -g npm@10
          npm ci
          npm run build
      - run: |
          rm -rf node_modules
      - name: Set version number
        uses: fjogeleit/yaml-update-action@dffe9a5223d84653c13374032382f6bb5de8e5ef #v0.17.0
        with:
          valueFile: 'slac.info.yml'
          propertyPath: 'version'
          value: '${{ github.ref_name }}'
          commitChange: false
      - name: Archive Release
        uses: thedoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554 #v0.7.6
        with:
          type: 'zip'
          filename: 'slac.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig source/*'
      - name: Upload Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd #v1.21.0
        with:
          artifacts: 'slac.zip'
          replacesArtifacts: true
          allowUpdates: true
  notify-satis:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697
        with:
          token: ${{ secrets.SATIS_REPO_TOKEN }}
          repository: slac-it/slac-drupal-satis
          event-type: release-published
          client-payload: >-
            {
              "package": "${{ github.repository }}",
              "version": "${{ github.ref_name }}"
